### ISSUE TITLE
FindViewModel over demands ViewModelBase

### ISSUE THREAD

**Issue by gdennie** [JonghoL/EventBindingMarkup#3]
EventBindingExtension.FindViewModel unnecessarily requires a ViewModelBase descendent when a non-null object should be sufficient or at most an INotifyPropertyChanged instance.

**Comment by JonghoL** [comment]
Command depends on the ViewModel. Of course ViewModelBase is generally desirable to implement INotifyPropertyChanged.

**Comment by gdennie** [comment]
Did not notice the use of Reflection Emit. Not familiar with it and am surprise it was necessary. Nice work.
